package com.payflow.domain

import jakarta.persistence.*
import java.time.OffsetDateTime
import java.util.*

@Entity
@Table(
    name = "payments",
    uniqueConstraints = [
        // Ensures idempotency at database level
        UniqueConstraint(name = "uk_idempotency_key", columnNames = ["idempotency_key"])
    ]
)
class Payment(

    // Primary identifier generated by the application
    @Id
    var id: UUID = UUID.randomUUID(),

    // Payment amount stored in minor units (eg cents)
    @Column(nullable = false)
    var amount: Long,

    // ISO currency code such as EUR
    @Column(nullable = false)
    var currency: String,

    // Current payment state used by the processing flow
    @Column(nullable = false)
    var status: String = "PENDING",           // PENDING | SUCCEEDED | FAILED

    // Used to prevent duplicate payment processing
    @Column(nullable = false, unique = true)
    var idempotencyKey: String,

    // Provider that handled the payment
    @Column(nullable = false)
    var provider: String = "unassigned",

    // Optional message returned by the provider
    @Column
    var message: String? = null,

    // Creation timestamp for audit and ordering
    @Column(nullable = false)
    var createdAt: OffsetDateTime = OffsetDateTime.now(),
)